# Test generated by RoostGPT for test vaiva-trial using AI Type Open AI and AI Model gpt-4

import unittest
from unittest.mock import patch
from jumbled_word_game import ask

class TestAsk(unittest.TestCase):
    
    def test_Ask_8e4149427b(self):
        # Test case 1: Correct answer
        with patch('builtins.input', return_value='apple'):
            self.assertEqual(ask('John', 1, 'apple'), True)

        # Test case 2: Incorrect answer
        with patch('builtins.input', return_value='orange'):
            self.assertEqual(ask('John', 1, 'apple'), False)

        # Test case 3: Empty answer
        with patch('builtins.input', return_value=''):
            self.assertEqual(ask('John', 1, 'apple'), False)

        # Test case 4: Case sensitive
        with patch('builtins.input', return_value='Apple'):
            self.assertEqual(ask('John', 1, 'apple'), False)

        # Test case 5: Non-alphabetic characters in answer
        with patch('builtins.input', return_value='appl3'):
            self.assertEqual(ask('John', 1, 'apple'), False)

if __name__ == '__main__':
    unittest.main()
