# Test generated by RoostGPT for test vaiva-trial using AI Type Open AI and AI Model gpt-4

import unittest
import random
from jumbled_word_game import choose_a_word

class TestChooseAWord(unittest.TestCase):
    
    def setUp(self):
        self.words = ['rainbow', 'computer', 'science', 'programming',
                        'mathematics', 'player', 'condition', 'reverse',
                        'water', 'board', 'account', 'administration', 'affect', 'agency', 'beyond']
    
    def test_Choose_a_word_f331355e57(self):
        
        # Test case 1: Check if the word returned is in the list of words
        word = choose_a_word()
        self.assertIn(word, self.words, f"Returned word {word} is not in the list")

        # Test case 2: Check if the function is truly random
        # Not a perfect test but a simple way to check randomness
        # Run the function 100 times and check if we get at least 10 unique words
        unique_words = set()
        for _ in range(100):
            unique_words.add(choose_a_word())
        self.assertTrue(len(unique_words) >= 10, "Function does not seem to be random")

if __name__ == "__main__":
    unittest.main()
