# Test generated by RoostGPT for test vaiva-trial using AI Type Open AI and AI Model gpt-4

import unittest
from unittest.mock import patch
from jumbled_word_game import continue_playing

class TestContinuePlaying(unittest.TestCase):
    @patch('builtins.input', return_value='X')
    def test_Continue_playing_bbb9bbd17b_X(self, input):
        self.assertEqual(continue_playing(), False, "The function should return False if user input is 'X'")

    @patch('builtins.input', return_value='x')
    def test_Continue_playing_bbb9bbd17b_x(self, input):
        self.assertEqual(continue_playing(), False, "The function should return False if user input is 'x'")

    @patch('builtins.input', return_value='Y')
    def test_Continue_playing_bbb9bbd17b_Y(self, input):
        self.assertEqual(continue_playing(), True, "The function should return True if user input is not 'X'")

    @patch('builtins.input', return_value='')
    def test_Continue_playing_bbb9bbd17b_empty(self, input):
        self.assertEqual(continue_playing(), True, "The function should return True if user input is empty")

if __name__ == '__main__':
    unittest.main()
