# Test generated by RoostGPT for test vaiva-trial using AI Type Open AI and AI Model gpt-4

# Importing necessary libraries
import unittest
from unittest.mock import patch
from io import StringIO

# Importing the method to be tested
from jumbled_word_game import check_win

class TestCheckWin(unittest.TestCase):

    # Test case 1: When there is a winner
    @patch('sys.stdout', new_callable=StringIO)
    def test_Check_win_45654bd252_winner(self, mock_stdout):
        # Mocking the score dictionary
        score = {"player1": 3, "player2": 4}
        # Calling the function
        check_win(score)
        # Checking the output
        self.assertEqual(mock_stdout.getvalue(), 'player1 won with 3 hits\n')

    # Test case 2: When there is no winner
    @patch('sys.stdout', new_callable=StringIO)
    def test_Check_win_45654bd252_no_winner(self, mock_stdout):
        # Mocking the score dictionary
        score = {}
        # Calling the function
        check_win(score)
        # Checking the output
        self.assertEqual(mock_stdout.getvalue(), 'Nobody won\n')

if __name__ == '__main__':
    unittest.main()
