# Test generated by RoostGPT for test vaiva-trial using AI Type Open AI and AI Model gpt-4

def thank_you_all(players, score):
    winning_score = 0
    per_score = dict()
    for p in players:
        print(f"{p}'s score is {score[p]}")
        if not per_score.get(score[p]):
            per_score[score[p]] = [p]
        else:
            per_score[score[p]].append(p)
        if score[p] > winning_score:
            winning_score = score[p]

    print(f'Winning score is {winning_score}')
    print('And the winner(s) are', ','.join(per_score[winning_score]))
    print('Thanks for playing !!!', ",".join(players).upper())
