# Test generated by RoostGPT for test vaiva-trial using AI Type Open AI and AI Model gpt-4

def welcome():
    welcome_message = "\n" + "*"*15 + " Welcome to MasterMind " + "*"*15 + "\n" + "*" * 53
    return welcome_message
